spring.application.name=sanosysalvos-bff
server.port=8084

# Rutas para conectarse a los microservicios que ya tienes corriendo
microservice.pet-report.url=http://localhost:8083
microservice.matching.url=http://localhost:8082
