spring.application.name=ms-pet-report
server.port=8083

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/sanos_salvos_core
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Archivos estáticos (imágenes)
spring.web.resources.static-locations=file:uploads/

# Subida de archivos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB