spring.application.name=ms-pet-report
server.port=8083

spring.datasource.url=jdbc:postgresql://postgres:5432/sanos_salvos_core
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect